wip

diff --git a/.github/workflows/build-syncthing.yaml b/.github/workflows/build-syncthing.yaml
--- a/.github/workflows/build-syncthing.yaml
+++ b/.github/workflows/build-syncthing.yaml
@@ -178,10 +178,12 @@ jobs:
 
       - name: Create packages
         run: |
-          go run build.go -goarch amd64 zip
-          go run build.go -goarch arm zip
-          go run build.go -goarch arm64 zip
-          go run build.go -goarch 386 zip
+          for tgt in syncthing stdiscosrv strelaysrv ; do
+            go run build.go -goarch amd64 zip $tgt
+            go run build.go -goarch arm zip $tgt
+            go run build.go -goarch arm64 zip $tgt
+            go run build.go -goarch 386 zip $tgt
+          done
         env:
           CGO_ENABLED: "0"
           CODESIGN_SIGNTOOL: ${{ secrets.CODESIGN_SIGNTOOL }}
@@ -229,7 +231,9 @@ jobs:
         run: |
           archs=$(go tool dist list | grep linux | sed 's#linux/##')
           for goarch in $archs ; do
-            go run build.go -goarch "$goarch" tar
+            for tgt in syncthing stdiscosrv strelaysrv ; do
+              go run build.go -goarch "$goarch" tar $tg
+            done
           done
         env:
           CGO_ENABLED: "0"
@@ -301,7 +305,9 @@ jobs:
 
       - name: Create package (amd64)
         run: |
-          go run build.go -goarch amd64 zip
+          for tgt in syncthing stdiscosrv strelaysrv ; do
+            go run build.go -goarch amd64 zip $tgt
+          done
         env:
           CGO_ENABLED: "1"
 
@@ -424,9 +430,11 @@ jobs:
             goos="${plat%/*}"
             goarch="${plat#*/}"
             echo "::group ::$plat"
-            if ! go run build.go -goos "$goos" -goarch "$goarch" tar 2>/dev/null; then
-              echo "::warning ::Failed to build for $plat"
-            fi
+            for tgt in syncthing stdiscosrv strelaysrv ; do
+              if ! go run build.go -goos "$goos" -goarch "$goarch" tar $tgt 2>/dev/null; then
+                echo "::warning ::Failed to build for $plat"
+              fi
+            done
             echo "::endgroup::"
           done
         env:
@@ -541,7 +549,7 @@ jobs:
           gpg --import < "$SIGNING_KEY"
 
           pushd packages
-          files=(*.tar.gz *.zip)
+          files=(syncthing*.tar.gz syncthing*.zip)
           sha1sum "${files[@]}" | gpg --clearsign > sha1sum.txt.asc
           sha256sum "${files[@]}" | gpg --clearsign > sha256sum.txt.asc
           gpg --sign --armour --detach syncthing-source-*.tar.gz
@@ -597,7 +605,9 @@ jobs:
       - name: Package for Debian
         run: |
           for arch in amd64 i386 armhf armel arm64 ; do
-            go run build.go -no-upgrade -installsuffix=no-upgrade -goarch "$arch" deb
+            for tgt in syncthing stdiscosrv strelaysrv ; do
+              go run build.go -no-upgrade -installsuffix=no-upgrade -goarch "$arch" deb $tgt
+            done
           done
         env:
           BUILD_USER: debian
